/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
        ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
        ElCollapse: typeof import('element-plus/es')['ElCollapse']
        ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
        ElDialog: typeof import('element-plus/es')['ElDialog']
        ElDivider: typeof import('element-plus/es')['ElDivider']
        ElDrawer: typeof import('element-plus/es')['ElDrawer']
        ElDropdown: typeof import('element-plus/es')['ElDropdown']
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElTabPane: typeof import('element-plus/es')['ElTabPane']
        ElTabs: typeof import('element-plus/es')['ElTabs']
        ElTag: typeof import('element-plus/es')['ElTag']
        ElUpload: typeof import('element-plus/es')['ElUpload']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        Tag: typeof import('./components/tag.vue')['default']
    }
}
